/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Ubicacion;
import Model.Unidades;
import static View.ViewUbicacion.CodigoUbicacion;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yoshi
 */
public class ViewUnidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewUbicacion
     */
    public ViewUnidad() {
        initComponents();
        confirmarjPanel.setVisible(false);
        mostar();
    }

void actualizarUnidad(){
        busquedajTextField.getDocument().addDocumentListener(new DocumentListener() {
            
            public void insertUpdate(DocumentEvent e) {
                limpiarTabla();
                BuquedaAnaquel();
            }

            public void removeUpdate(DocumentEvent e) {
               limpiarTabla();
            }

            public void changedUpdate(DocumentEvent e) {
             limpiarTabla();
             BuquedaAnaquel();
            }

        });
    }
void BuquedaAnaquel()
    {
        List<Unidades>consultar = Controller.ConsultasMateriales.ListaUnidades(busquedajTextField.getText());
        //para saber si hay elemtos en la lista
        if(consultar.size()>0){
        Iterator elemento=consultar.iterator();
        //hasNext()= si hay un elemto adelante avanzar
        while(elemento.hasNext())
        {
           DefaultTableModel datos=(DefaultTableModel)unidadjTable.getModel();
        //El vector es para agregar datos a la tabla
        Vector resultado=new Vector();      
        Unidades registro=(Unidades)elemento.next();
        resultado.add(registro.getIdUnidades());
        resultado.add(registro.getUnidad());
        datos.addRow(resultado);
        }
    }
    }
void mostar()
    {
        List<Unidades>consultar = Controller.ConsultasMateriales.ListaUnidades();
        //para saber si hay elemtos en la lista
        if(consultar.size()>0){
        Iterator elemento=consultar.iterator();
        //hasNext()= si hay un elemto adelante avanzar
        while(elemento.hasNext())
        {
           DefaultTableModel datos=(DefaultTableModel)unidadjTable.getModel();
        //El vector es para agregar datos a la tabla
        Vector resultado=new Vector();      
        Unidades registro=(Unidades)elemento.next();
        resultado.add(registro.getIdUnidades());
        resultado.add(registro.getUnidad());
        datos.addRow(resultado);
        }
        }else{
            System.out.print("No hay registros a mostrar");
        }
    }

void limpiarTabla()
    {
        while (unidadjTable.getRowCount()!=0)
        {
         ((DefaultTableModel)unidadjTable.getModel()).removeRow(0);
        }
    }
void ChoiseUnidad(){
        if(unidadjTable.getSelectedRow()>=0){
            confirmarjPanel.setVisible(true);
        }else{
            confirmarjPanel.setVisible(false);
        }
    }
public static Unidades CodigoUnidad(int ubicacion){
        Unidades idUnidad= Controller.ConsultasMateriales.UnicaUnidad(ubicacion);
        if(idUnidad!=null){
            return idUnidad;
        }else{
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unidadjTextField = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        searchjPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        busquedajTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        unidadjTable = new javax.swing.JTable();
        confirmarjPanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ubicacion");
        setToolTipText("Agrega la ubicacion");

        newjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir una nueva Unidad"));

        jLabel1.setText("Unidad:");

        savejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/save.png"))); // NOI18N
        savejButton.setToolTipText("Guardar Cambios");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        canceljButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/cancel.png"))); // NOI18N
        canceljButton.setToolTipText("Cancelar ");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newjPanelLayout = new javax.swing.GroupLayout(newjPanel);
        newjPanel.setLayout(newjPanelLayout);
        newjPanelLayout.setHorizontalGroup(
            newjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newjPanelLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unidadjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(savejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canceljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        newjPanelLayout.setVerticalGroup(
            newjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(canceljButton)
                    .addComponent(savejButton)
                    .addGroup(newjPanelLayout.createSequentialGroup()
                        .addGroup(newjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(unidadjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        searchjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar:"));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/search.png"))); // NOI18N
        jLabel4.setText("Unidad:");

        javax.swing.GroupLayout searchjPanelLayout = new javax.swing.GroupLayout(searchjPanel);
        searchjPanel.setLayout(searchjPanelLayout);
        searchjPanelLayout.setHorizontalGroup(
            searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchjPanelLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(busquedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchjPanelLayout.setVerticalGroup(
            searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchjPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(searchjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(busquedajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        unidadjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        unidadjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidadjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(unidadjTable);
        unidadjTable.getColumnModel().getColumn(0).setResizable(false);
        unidadjTable.getColumnModel().getColumn(1).setResizable(false);

        confirmarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elegir una unidad de medicion:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/Yes.png"))); // NOI18N
        jToggleButton1.setText("Confirmar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/No.png"))); // NOI18N
        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmarjPanelLayout = new javax.swing.GroupLayout(confirmarjPanel);
        confirmarjPanel.setLayout(confirmarjPanelLayout);
        confirmarjPanelLayout.setHorizontalGroup(
            confirmarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmarjPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmarjPanelLayout.setVerticalGroup(
            confirmarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmarjPanelLayout.createSequentialGroup()
                .addGroup(confirmarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(confirmarjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        if(!unidadjTextField.getText().isEmpty())
        {
            if(Controller.ControllerUnidades.CreateUnidad(unidadjTextField.getText())==true)
            {
              JOptionPane.showMessageDialog(null, "Agregado correctamente","Operacion exitosa",JOptionPane.INFORMATION_MESSAGE);
              limpiarTabla();
              mostar();
              unidadjTextField.setText("");
            }else{
              JOptionPane.showMessageDialog(null, "No se ha podido agregar \nIntente mas tarde","Operacion fallida",JOptionPane.ERROR_MESSAGE);               
            }
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        unidadjTextField.setText("");
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void unidadjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadjTableMouseClicked
        ChoiseUnidad();
    }//GEN-LAST:event_unidadjTableMouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        unidadjTable.clearSelection();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       if(unidadjTable.getSelectedRow()>-1)
       {
        int selected = unidadjTable.getSelectedRow();                  
        String id=unidadjTable.getValueAt(selected, 0).toString();
        String unidad=unidadjTable.getValueAt(selected, 1).toString();    
        int confirm= JOptionPane.showConfirmDialog(null, "¿Esta seguro?");
        if(confirm==0)
        {
//            ViewMateriales s =new ViewMateriales();
//            Principal.jDesktopPane1.add(s);
//            s.CargarMateriales(Integer.parseInt(id));
//            s.show();
//            JOptionPane.showMessageDialog(null, "La fila seleccionada es: "+nombre);
//            dispose();
              ViewMateriales.unidadjTextField.setText(unidad);
              ViewMateriales.idUnidad=CodigoUnidad(Integer.parseInt(id));
              this.dispose();
              //JOptionPane.showMessageDialog(null, ViewMateriales.idUnidad.getUnidad());
        }else{
            JOptionPane.showMessageDialog(null, "Se ha cancelado");
            unidadjTable.clearSelection();
        }
       }else{
           JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila","Error de Seleccion",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedajTextField;
    private javax.swing.JButton canceljButton;
    private javax.swing.JPanel confirmarjPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel newjPanel;
    private javax.swing.JButton savejButton;
    private javax.swing.JPanel searchjPanel;
    private javax.swing.JTable unidadjTable;
    private javax.swing.JTextField unidadjTextField;
    // End of variables declaration//GEN-END:variables
}
