package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private Integer idAdministrador;
     private String nombre;
     private String contrasena;
     private String tipo;
     private Set<Entradas> entradases = new HashSet<Entradas>(0);
     private Set<Devoluciones> devolucioneses = new HashSet<Devoluciones>(0);

    public Administrador() {
    }

	
    public Administrador(String nombre, String contrasena, String tipo) {
        this.nombre = nombre;
        this.contrasena = contrasena;
        this.tipo = tipo;
    }
    public Administrador(String nombre, String contrasena, String tipo, Set<Entradas> entradases, Set<Devoluciones> devolucioneses) {
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.tipo = tipo;
       this.entradases = entradases;
       this.devolucioneses = devolucioneses;
    }
   
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Entradas> getEntradases() {
        return this.entradases;
    }
    
    public void setEntradases(Set<Entradas> entradases) {
        this.entradases = entradases;
    }
    public Set<Devoluciones> getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set<Devoluciones> devolucioneses) {
        this.devolucioneses = devolucioneses;
    }




}


