package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private Integer idArea;
     private String area;
     private String encargado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Areas() {
    }

	
    public Areas(String area, String encargado) {
        this.area = area;
        this.encargado = encargado;
    }
    public Areas(String area, String encargado, Set<Usuario> usuarios) {
       this.area = area;
       this.encargado = encargado;
       this.usuarios = usuarios;
    }
   
    public Integer getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(Integer idArea) {
        this.idArea = idArea;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(String encargado) {
        this.encargado = encargado;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


