package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Detallesmateriales generated by hbm2java
 */
public class Detallesmateriales  implements java.io.Serializable {


     private Integer idDetalleMaterial;
     private Unidades unidades;
     private Materiales materiales;
     private String codigo;
     private float stock;
     private Date fechaCaducidad;
     private String detalles;

    public Detallesmateriales() {
    }

	
    public Detallesmateriales(Unidades unidades, Materiales materiales, String codigo, float stock) {
        this.unidades = unidades;
        this.materiales = materiales;
        this.codigo = codigo;
        this.stock = stock;
    }
    public Detallesmateriales(Unidades unidades, Materiales materiales, String codigo, float stock, Date fechaCaducidad, String detalles) {
       this.unidades = unidades;
       this.materiales = materiales;
       this.codigo = codigo;
       this.stock = stock;
       this.fechaCaducidad = fechaCaducidad;
       this.detalles = detalles;
    }
   
    public Integer getIdDetalleMaterial() {
        return this.idDetalleMaterial;
    }
    
    public void setIdDetalleMaterial(Integer idDetalleMaterial) {
        this.idDetalleMaterial = idDetalleMaterial;
    }
    public Unidades getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Unidades unidades) {
        this.unidades = unidades;
    }
    public Materiales getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Materiales materiales) {
        this.materiales = materiales;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public float getStock() {
        return this.stock;
    }
    
    public void setStock(float stock) {
        this.stock = stock;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }




}


