package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA



/**
 * Detallespedidos generated by hbm2java
 */
public class Detallespedidos  implements java.io.Serializable {


     private Integer idDetallePedido;
     private Requesiciones requesiciones;
     private Pedidos pedidos;
     private Materiales materiales;
     private float cantidad;

    public Detallespedidos() {
    }

    public Detallespedidos(Requesiciones requesiciones, Pedidos pedidos, Materiales materiales, float cantidad) {
       this.requesiciones = requesiciones;
       this.pedidos = pedidos;
       this.materiales = materiales;
       this.cantidad = cantidad;
    }
   
    public Integer getIdDetallePedido() {
        return this.idDetallePedido;
    }
    
    public void setIdDetallePedido(Integer idDetallePedido) {
        this.idDetallePedido = idDetallePedido;
    }
    public Requesiciones getRequesiciones() {
        return this.requesiciones;
    }
    
    public void setRequesiciones(Requesiciones requesiciones) {
        this.requesiciones = requesiciones;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Materiales getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Materiales materiales) {
        this.materiales = materiales;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


