package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Devoluciones generated by hbm2java
 */
public class Devoluciones  implements java.io.Serializable {


     private Integer idDevolucion;
     private Estado estado;
     private Administrador administrador;
     private Salidas salidas;
     private Date fechaDevolucion;
     private float cantidad;

    public Devoluciones() {
    }

    public Devoluciones(Estado estado, Administrador administrador, Salidas salidas, Date fechaDevolucion, float cantidad) {
       this.estado = estado;
       this.administrador = administrador;
       this.salidas = salidas;
       this.fechaDevolucion = fechaDevolucion;
       this.cantidad = cantidad;
    }
   
    public Integer getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(Integer idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public Salidas getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Salidas salidas) {
        this.salidas = salidas;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


