package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Entradas generated by hbm2java
 */
public class Entradas  implements java.io.Serializable {


     private Integer idEntradas;
     private Administrador administrador;
     private Materiales materiales;
     private Date fechaEntrada;

    public Entradas() {
    }

    public Entradas(Administrador administrador, Materiales materiales, Date fechaEntrada) {
       this.administrador = administrador;
       this.materiales = materiales;
       this.fechaEntrada = fechaEntrada;
    }
   
    public Integer getIdEntradas() {
        return this.idEntradas;
    }
    
    public void setIdEntradas(Integer idEntradas) {
        this.idEntradas = idEntradas;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public Materiales getMateriales() {
        return this.materiales;
    }
    
    public void setMateriales(Materiales materiales) {
        this.materiales = materiales;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }




}


