package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String estado;
     private Set<Devoluciones> devolucioneses = new HashSet<Devoluciones>(0);
     private Set<Materiales> materialeses = new HashSet<Materiales>(0);

    public Estado() {
    }

	
    public Estado(String estado) {
        this.estado = estado;
    }
    public Estado(String estado, Set<Devoluciones> devolucioneses, Set<Materiales> materialeses) {
       this.estado = estado;
       this.devolucioneses = devolucioneses;
       this.materialeses = materialeses;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Devoluciones> getDevolucioneses() {
        return this.devolucioneses;
    }
    
    public void setDevolucioneses(Set<Devoluciones> devolucioneses) {
        this.devolucioneses = devolucioneses;
    }
    public Set<Materiales> getMaterialeses() {
        return this.materialeses;
    }
    
    public void setMaterialeses(Set<Materiales> materialeses) {
        this.materialeses = materialeses;
    }




}


