package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private Integer idMarca;
     private String marca;
     private Set<Materiales> materialeses = new HashSet<Materiales>(0);

    public Marcas() {
    }

	
    public Marcas(String marca) {
        this.marca = marca;
    }
    public Marcas(String marca, Set<Materiales> materialeses) {
       this.marca = marca;
       this.materialeses = materialeses;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Set<Materiales> getMaterialeses() {
        return this.materialeses;
    }
    
    public void setMaterialeses(Set<Materiales> materialeses) {
        this.materialeses = materialeses;
    }




}


