package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Materiales generated by hbm2java
 */
public class Materiales  implements java.io.Serializable {


     private Integer idMateriales;
     private Estado estado;
     private Marcas marcas;
     private Ubicacion ubicacion;
     private String material;
     private String imagen;
     private boolean activo;
     private Set<Entradas> entradases = new HashSet<Entradas>(0);
     private Set<Detallesmateriales> detallesmaterialeses = new HashSet<Detallesmateriales>(0);
     private Set<Detallespedidos> detallespedidoses = new HashSet<Detallespedidos>(0);

    public Materiales() {
    }

	
    public Materiales(Estado estado, Marcas marcas, Ubicacion ubicacion, String material, boolean activo) {
        this.estado = estado;
        this.marcas = marcas;
        this.ubicacion = ubicacion;
        this.material = material;
        this.activo = activo;
    }
    public Materiales(Estado estado, Marcas marcas, Ubicacion ubicacion, String material, String imagen, boolean activo, Set<Entradas> entradases, Set<Detallesmateriales> detallesmaterialeses, Set<Detallespedidos> detallespedidoses) {
       this.estado = estado;
       this.marcas = marcas;
       this.ubicacion = ubicacion;
       this.material = material;
       this.imagen = imagen;
       this.activo = activo;
       this.entradases = entradases;
       this.detallesmaterialeses = detallesmaterialeses;
       this.detallespedidoses = detallespedidoses;
    }
   
    public Integer getIdMateriales() {
        return this.idMateriales;
    }
    
    public void setIdMateriales(Integer idMateriales) {
        this.idMateriales = idMateriales;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Entradas> getEntradases() {
        return this.entradases;
    }
    
    public void setEntradases(Set<Entradas> entradases) {
        this.entradases = entradases;
    }
    public Set<Detallesmateriales> getDetallesmaterialeses() {
        return this.detallesmaterialeses;
    }
    
    public void setDetallesmaterialeses(Set<Detallesmateriales> detallesmaterialeses) {
        this.detallesmaterialeses = detallesmaterialeses;
    }
    public Set<Detallespedidos> getDetallespedidoses() {
        return this.detallespedidoses;
    }
    
    public void setDetallespedidoses(Set<Detallespedidos> detallespedidoses) {
        this.detallespedidoses = detallespedidoses;
    }




}


