package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedidos;
     private Usuario usuario;
     private Date fechaPedido;
     private Set<Salidas> salidases = new HashSet<Salidas>(0);
     private Set<Detallespedidos> detallespedidoses = new HashSet<Detallespedidos>(0);

    public Pedidos() {
    }

	
    public Pedidos(Usuario usuario, Date fechaPedido) {
        this.usuario = usuario;
        this.fechaPedido = fechaPedido;
    }
    public Pedidos(Usuario usuario, Date fechaPedido, Set<Salidas> salidases, Set<Detallespedidos> detallespedidoses) {
       this.usuario = usuario;
       this.fechaPedido = fechaPedido;
       this.salidases = salidases;
       this.detallespedidoses = detallespedidoses;
    }
   
    public Integer getIdPedidos() {
        return this.idPedidos;
    }
    
    public void setIdPedidos(Integer idPedidos) {
        this.idPedidos = idPedidos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Set<Salidas> getSalidases() {
        return this.salidases;
    }
    
    public void setSalidases(Set<Salidas> salidases) {
        this.salidases = salidases;
    }
    public Set<Detallespedidos> getDetallespedidoses() {
        return this.detallespedidoses;
    }
    
    public void setDetallespedidoses(Set<Detallespedidos> detallespedidoses) {
        this.detallespedidoses = detallespedidoses;
    }




}


