package Model;
// Generated 16/12/2013 11:11:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Areas areas;
     private String usuario;
     private String contrasena;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public Usuario() {
    }

	
    public Usuario(Areas areas, String usuario, String contrasena) {
        this.areas = areas;
        this.usuario = usuario;
        this.contrasena = contrasena;
    }
    public Usuario(Areas areas, String usuario, String contrasena, Set<Pedidos> pedidoses) {
       this.areas = areas;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.pedidoses = pedidoses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


